version: '3.1'
services:
  db:
    image: mysql
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: springboot-kotlin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
  app:
    image: springboot-kotlin
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springboot-kotlin?autoreconnect=true
      SPRING_JPA_DATABASE: mysql
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

volumes:
  mysql_data: