GET http://127.0.0.1:8080/api/customers/316a59a0-78f1-4168-8a5a-4e2a75616ffb
Accept: application/json

###


POST http://127.0.0.1:8080/api/customers
Accept: application/json
Content-Type: application/json

{
  "name": "CodeKata"
}

###