GET http://127.0.0.1:8080/api/customers/1
Accept: application/json

###


POST http://127.0.0.1:8080/api/customers
Accept: application/json
Content-Type: application/json

{
  "name": "CodeKata"
}

###

PUT http://127.0.0.1:8080/api/customers/2
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "name": "CodingDojo"
}

###

DELETE http://127.0.0.1:8080/api/customers/1

###

GET http://127.0.0.1:8080/api/customers
Accept: application/json

###
